### ISSUE TITLE
correlate returns Inf with standard normals

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/fabricatr#106]
```r
set.seed(123)
pop <- fabricate(
  N = 1000, 
  e1 = rnorm(N),
  e2 = correlate(given = e1,
                 rho = .2,
                 rnorm)
)
cor(pop$e1,pop$e2)
pop[is.infinite(pop$e2),]
```

**Comment by aaronrudkin** [comment]
This is taken care of on the `rec_change` branch, which should be merged into master soon; issue is basically that the `ecdf(x)(x)` function often selects quantile 1, which with the normal outcome gives you Inf. We switched to using `rank(x) / length(x) + 1`, which tiebreaks sanely, doesn't change the math, and should avoid pushing anything out to infinity.

**Comment by aaronrudkin** [comment]
This is merged in.

**Comment by aaronrudkin** [comment]
Neal ran some simulations to confirm the update is such that we'd need in the order of 10^18 sample size to generate an Inf value under the fixed version; per our discussion on Monday, I think that probably suggests we don't need to do any alterations beyond what's implemented.
