### ISSUE TITLE
Scalar probabilities in draw_binary not working when wrapped in fabricate

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/fabricatr#109]
This works great:
```
draw_binary(prob = .5,N = 10)
```
But at the moment this returns either all 0s or all 1s
```
fabricate(N = 10,X = draw_binary(prob = .5))
```

**Comment by jaspercooper** [comment]
This works, so I suspect N is just not being passed to draw_binary() when you pass a scalar to prob
```
fabricate(N = 10,X = draw_binary(N = N,prob = .5))
```

**Comment by aaronrudkin** [comment]
Correct; N is not automatically fed in there. It would probably be useful to do that by default though.

**Comment by graemeblair** [comment]
+1 to doing that by default!

**Comment by aaronrudkin** [comment]
Note to self: The dynGet strategy we use for recycle would work here if just putting it in the formals doesn't.

**Comment by aaronrudkin** [comment]
I just had a random thought about this -- the will be a slightly breaking change. Currently the default N when none is specified is `length(prob)` -- which is great if you are passing 10 probabilities for 10 observations, but not great if you are passing 1 probability for 10 observations. This is a legacy of the version of **fabricatr** I inherited, but also strikes me as probably a pretty good default behaviour.

Implementing the implicit N lookup to do this would require supplying no default value for N, or having a more complicated hierarchy of defaults (i.e. if this is inside a fabricate call and no N is supplied, try to find an N, and if not, then try to guess N is length(prob)). That seems reasonable, although breaking for current users.

Trivial technical implementation, but maybe worth having a little discussion on the concept. At some point we will want to stop making any kind of breaking changes on users, maybe we're still early enough we don't need to worry about it though.

**Comment by graemeblair** [comment]
this works now
