### ISSUE TITLE
correlate documentation

### ISSUE THREAD

**Issue by medinali** [DeclareDesign/fabricatr#113]
-  Documentation does not have section **Value**

- The description reads  "the result ensures, in expectation, a rank-order correlation of 'rho'".
But the actual correlation it's not always right in expectation. Maybe the documentation should describe the data generating process and the variance.

**Comment by medinali** [comment]
For instance, if one takes any rho and replicates function correlate gets

`
rho = 0.5
exam_score <- pmin(100, rnorm(n = 100, mean = 80, sd = 10))

DF_cor <- replicate(1000,  correlate(given = exam_score, rho = rho,
                              draw_binomial, prob = 0.7, trials = 100, N = 1000))

r <- apply(DF_cor, MARGIN = 2, cor, exam_score, method = "spearman")

hist(r)
abline(v = c(mean(r), rho), col = c("red", "blue") , lty= c(2, 1), lwd= 3)
`
![histogram](https://user-images.githubusercontent.com/22347212/38414632-56a9aa16-398f-11e8-9435-8df5223a7fa9.png)

So the rank-order correlation is close but often off. 
Also given the description, I was expecting to see the mean of the correlation a bit closer to rho.

**Comment by macartan** [comment]
Note we could have a function that provides an exact correlation, rather
than in expectation, at least for rnorm. Not sure though if this can be
generalized easily:

corvar <- function (given, rho=0, mean=0, sd=1) {
  u <- rnorm(length(given))
  z <- rho * scale(given)[,1] + sqrt(1 - rho^2) * scale(resid(lm(u ~
given)))[,1]
  return(mean + sd * z)
}

> x <- rnorm(10)> y <- corvar(x, -.909)> cor(x,y)[1] -0.909
