### ISSUE TITLE
2 notes on documentation

### ISSUE THREAD

**Issue by medinali** [DeclareDesign/fabricatr#114]
- In the first example of function **fabricate**` head(df) `should be corrected to `head(multi_level_df)`

```
 # Draw a two-level hierarchical dataset
 # containing cities within regions
    multi_level_df <- fabricate(
    regions = add_level(N = 5),
    cities = add_level(N = 2, pollution = rnorm(N, mean = 5)))
    head(df)
```

- functions join and recycle have no examples in the documentation.

**Comment by aaronrudkin** [comment]
Thank you very much for this feedback -- both of these are, of course, omissions/errors on our part. I will push a fix ASAP.

**Comment by nfultz** [comment]
Suggest moving join() docs into the cross classify page.
