### ISSUE TITLE
allow cross-classified levels with common upper levels

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#117]
Take the primary and secondary school districts example, where the two are not nested. If I understand correctly, it's not possible to say each primary and secondary school are each nested in a common set of counties. So we'd want to draw states then counties then, separately, primary and secondary school districts within each county. This could be done through hackery, but I've now run into a couple use cases where this would be useful directly.

This is perhaps a better way to handle this, using levels rather than custom variable creation: https://github.com/DeclareDesign/fabricatr/issues/91

**Comment by nfultz** [comment]
This should be possible now, but is probably not documented.

**Comment by graemeblair** [comment]
Thanks Neal. Do you mind pointing me to how this should work? I put together this working example, based on the above. I don't know how to link secondary schools to states.

```
students_uncorr <- fabricate(
    states          = add_level(
      N = 2,
      state_name = c("NJ", "NY"),
      school_quality = runif(N)
    ),
    primary_schools = add_level(
      N = 5,
      ps_quality = runif(n = N, 1, 100),
    ),
    secondary_schools = add_level(
      N = 5,
      ss_quality = runif(n = N, 1, 100),
      nest = FALSE
    ),
    students = link_levels(
      N = 2,
      by = join(ps_quality, ss_quality, rho = 0),
      student_score = ps_quality * 5 + ss_quality * 10 + rnorm(N, 10, 5),
    )
  )
```

**Comment by nfultz** [comment]
The diamond graph is minimally tested in https://github.com/DeclareDesign/fabricatr/blob/master/tests/testthat/test-crossclassified.R#L362

The trick is to use modify_level to "reactivate" the parent, then nest from it again.

 I think it would be nicer if we changed the nest argument to be false = new level, true = last level, text = id of parent explicitly provided.

**Comment by acoppock** [comment]
I think that solution sounds great -- @nfultz, would you be able to implement that approach in the near future?
