### ISSUE TITLE
unnecessary warning?

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#121]
This feels like overkill:

```
> draw_categorical(N = N, prob = rep(.25, 4), category_labels = 1:4)
For a categorical (multinomial) distribution, a matrix of probabilities should be provided. The data below is generated by interpreting the vector of category probabilities you provided as identical for each observation.
```

**Comment by nfultz** [comment]
Also it isn't multinomial, so should ellide it.

**Comment by aaronrudkin** [comment]
This was originally a warning and is now a message, and I agree should probably be removed.

**Comment by aaronrudkin** [comment]
This is removed in the commit I just placed. This also deprecated a test designed to test this line. I commented out but did not remove the test (useful to keep a record that we had originally messaged on this functionality). Feel free to remove test if you think the visual clutter exceeds the value of keeping the record of the deprecated test.
