### ISSUE TITLE
Using lower levels to define upper level

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/fabricatr#124]
I am working with an case where I need to make use of a block level mean in an existing dataset to set to generate new data at the block level; creating a variable like "mean_u" below is not currently allowed however. There are workarounds but being able to do this directly as below would be useful:

```
df <- fabricate(block = add_level(N = 2),
                  i      = add_level(N = 2, u =rnorm(N)))

df <- fabricate(data = df,
                block = modify_level(mean_u = mean(u)))  
```
produces:

```
Error in modify_level_internal(N = N, ID_label = ID_label, working_environment_ = working_environment_,  : 
  Your modify_level command attempts to generate a new variable at the level "block" but requires reading from the existing variable(s) [u] which are not defined at the level "block"

To prevent this error, you may modify the data at the level of interest, or change the definition of your new variables.
```

**Comment by jaspercooper** [comment]
Agree it would be nice to have a direct implementation, but just wanted to point out I have found a reasonably straightforward way to do this in the past in base `R` using `ave()`:

```
    population <- declare_population(
      country = add_level(
        N_countries,
        country_effect = rnorm(N),
        country_trend = seq(min_trend, max_trend, length.out = N_countries)
      ),
      years = add_level(
        N_years,
        year = start_year:(start_year + N_years - 1),
        year_effect = rnorm(N),
        year_effect = ave(year_effect, year),
        noise = rnorm(N),
        trend = (year / 1000) * country_trend,
        shock = fabricatr::draw_binary(latent = trend, link = "probit")
      )
    )
```

I can't test right now but I think in your case it should be possible using
```r
df <- fabricate(block = add_level(N = 2),
                  i      = add_level(N = 2, u =rnorm(N), mean_u = ave(u,block)
))
```

**Comment by aaronrudkin** [comment]
Currently ave is the correct strategy for this -- we have documentation on this in the "Building and Importing Data" vignette, but it's a little buried. https://declaredesign.org/r/fabricatr/articles/building_importing.html#averages-within-higher-levels-of-hierarchy

I think GB and I will be discussing over the next little while the pain points related to reaching across levels; you can see from the other open issues we have here what some of those are.

**Comment by macartan** [comment]
Realize there may be no easy solution here but note the kind of use case I
have in mind is one where you need say on level 1 an average of some var on
level 2 and then you use that on level 1 to produce other content; the ave
approach requires either multiple going up and down levels or doing
everything at the lower level. Both work but not terribly neat.
