### ISSUE TITLE
Travis has not yet cut over to R3.4/3.5

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#125]
Thus, our current test matrix is 3.3/3.4, and all of our oldrel builds will fail because we no longer support 3.3.

This is not really something we can fix, but I think it's smart to keep an open issue on it until Travis fixes, which they might not because they are also pushing some thing to cut over open source projects from Travis-CI.org to Travis-CI.com and my understanding is those are parallel infrastructures.

**Comment by nfultz** [comment]
Looks fixed, closing this.
