### ISSUE TITLE
multivariate draws

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/fabricatr#127]
We have a curious issue with the use of correlate in the two arm design. We draw u_0 and u_1 as correlated variables in order to produce correlated Y_0, Y_1 potential outcomes. 

That seems OK but, a little subtly, multiple applications of this procedure do not produce vectors of outcomes with the right correlation; one is in a sense drawing many clusters since the second vector *depends* on the first; they are not commonly drawn from the same distribution. 

This would not be a problem with true draws from a multivariate distribution.

To illustrate:

```{r}
library(DesignLibrary)
```

```{r}
design_4 <- simple_two_arm_designer(N = 4, rho = .5)
df_4     <- draw_data(design_4)
for(j in 1:250) df_4 <- rbind(df_4, draw_data(design_4))
with(df_4, cor(u_0, u_1))
```
```
## [1] 0.2243488
```
Far from 0.5.

This repeated application of draw_data reveals that the individual draws are not random draws from the bivariate distribution of interest.

Compare with:

```{r}
design_1000 <- simple_two_arm_designer(N = 1000, rho = .5)
df_1000 <- draw_data(design_1000)
with(df_1000, cor(u_0, u_1))
```
```
## [1] 0.5152048
```
Here is a solution that draws the variables simultaneously

```{r}
library(MASS)

add_mvn <- function(data, names = c("V1", "V2"), m1=0, m2=0, sd1=1, sd2=1, rho=0){
  N   <- nrow(data)  
  Rho <- matrix(c(1, rho, rho, 1),2,2)
  sd  <- c(sd1, sd2)
  Sigma <- sweep(sweep(Rho, 1L, sd, "*"), 2L, sd, "*")

  add <- mvrnorm(n = N, mu = c(m1, m2), Sigma, tol = 1e-6, empirical = FALSE, EISPACK = FALSE)
  colnames(add) <- names
  cbind(data, add)
}

U <- declare_population(N = 4)
V <- declare_step(handler = add_mvn, names = c("u_0", "u_1"), rho = .5)

design <- U/V

df <- draw_data(design)
for(j in 1:250) df <- rbind(df, draw_data(design))
with(df, cor(u_0, u_1))
```

```
## [1] 0.4755442
```

**Question**: can we get something like `add_mvn` into `fabricatr`? Requires assigning multiple variables at once.

**Comment by acoppock** [comment]
I think this is related to https://github.com/DeclareDesign/fabricatr/issues/93 ?  Definitely something we want.  

Is it true that part of the problem is that `correlate` is biased and the bias is worse in smaller samples? (so when we aggregate many small samples, the bias doesn't go away)?

**Comment by macartan** [comment]
Yes, seems to be related to that


```{r}
design_4 <- simple_two_arm_designer(N = 4, rho = .5)
rs <- replicate(250, with(draw_data(design_4), cor(u_0, u_1)))
mean(rs)
```

0.3147001

**Comment by nfultz** [comment]
This probably applies generally to all designs with hierachical data. 

For this case specifically, I think there are several issues:
  * small sample size
  * there is an interaction between the small sample size and the `cor` estimate.
  * `correlate` is attenuated because it is conditioned on a single realization.
  * each `draw_data`s produces a different mixture component and aggregating those can be bad.

Even using the multivariate draw, stock `cor` is pretty biased / skewed:

```
> summary(replicate(25000, cor(MASS::mvrnorm(4, 1:2, matrix(c(1,.4, .4, 1), 2,2)))[1,2]))
        Min.      1st Qu.       Median         Mean      3rd Qu.         Max. 
-0.998413267 -0.003738231  0.481873897  0.344734395  0.788961304  0.999988906
```

`cor` is nonlinear, so perhaps this shouldn't be surprising.


#93 will support multivariate draws, but the design will need to be altered if you want .4 to come out when you call `simple_two_arm_designer(N = 4, rho = .4)`.

**Comment by nfultz** [comment]
Also note from ?correlate:

```
The result ensures, in expectation, a rank-order correlation of `rho`.
```

we shouldn't bury the lede there.

**Comment by graemeblair** [comment]
Since we have the function `draw_multivariate` which allows the use of mvrnorm and other functions that draw multivariate random variables, e.g.:

```
fabricate(
  N = 100,
  draw_multivariate(c(Y_1, Y_2) ~ mvrnorm(
     n = N,
     mu = c(0, 0),
     Sigma = matrix(c(10, 3, 3, 2), 2, 2)
  ))
)
```
