### ISSUE TITLE
Remove link argument from draw_categorical 

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/fabricatr#129]
```r
draw_categorical(prob = runif(4),N = 100, link = "identity")
draw_categorical(prob = runif(4),N = 100, link = "logit")
```
Second line produces following error
> `Categorical data does not accept link functions.`

So why not simply remove it?

**Comment by aaronrudkin** [comment]
Mea culpa on this, I thought there was an roxygen limitation that required conformable arguments when you re-used docs. There isn't. Closed in a commit.
