### ISSUE TITLE
message when passing data with a variable called N

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/fabricatr#130]
```
> data = data.frame(N = 1:3)
> fabricate(data, M = 2)
Error: `data` must be uniquely named but has duplicate elements
```

diagnosands dataframes might often have a variable called "N" in them since that it a dimension along which expand_design likely operates; special use of N in fabricatr means it cannot be used in these.  That's a cost. 

* Useful to have a warning of the form : "fabricatr cannot accept dataframes with variables named N"
* Better, perhaps: temporarily rename N, implement operations, then restore name
* Better, perhaps, though possibly too late: use a more obscure name for fabricator's N.

**Comment by nfultz** [comment]
This seems like a internal implementation bug; but why would you ever pass
a diagnosand output to fabricate?

**Comment by macartan** [comment]
Thabks. In this case for some analysis of the simulations_df that requires
manipulating output. In general though it's hard to predict usage.

Great if there were a fix to this.
