### ISSUE TITLE
changing categories in draw_ordered

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/fabricatr#134]
Currently the use of breaks seems to depend on the values of the latent variable provided. 

Below breaks are meant to indicate 1 if <1/3, 2 if in [1/3,2/3], 3 if > 2/3

But in fact categories jump around

```
> draw_ordered(c(.5, .5, .5), breaks = c(1/3, 2/3)) 
[1] 1 1 1
> draw_ordered(c(.3, .5, .5), breaks = c(1/3, 2/3)) 
[1] 1 2 2
> draw_ordered(c(.5, .5, .7), breaks = c(1/3, 2/3))
[1] 1 1 2
```

**Comment by nfultz** [comment]
I think we should just do whatever findInterval does instead of the heuristics implemented in draw_ordered.

**Comment by nfultz** [comment]
An alternative would be to set the OOB points to NA.
