### ISSUE TITLE
correlate documentation -- truth in advertising

### ISSUE THREAD

**Issue by macartan** [DeclareDesign/fabricatr#144]
Thi swe decided that this is not quite true for small N or because of constraints from limited vars?: 

"The result ensures, in expectation, a rank-order correlation of 'rho'."

**Comment by macartan** [comment]
Are we sure also that the claim about ICC is also true in expectation for all data structures?

**Comment by graemeblair** [comment]
Added clear backpedaling of claims; we need to do more sims or analytical work to figure out what the general properties are.
