### ISSUE TITLE
Categorical data generation needs sane defaults

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#15]
Currently categorical data generation expects a matrix of probabilities. So, for instance, if you have a population of size 10 that is generated to have a partisan affiliation (D, R, I with some probability on each), draw_discrete expects a 10x3 matrix of probabilities and hard errors if provided with the vector c(0.4, 0.3, 0.3).

The matrix model makes sense if someone is simulation a population with heterogeneity with respect to the probabilities between units -- the vignette example is like this. I would expect, though, that more users would want to make N i.i.d. draws from a categorical distribution.

If there's no strong objection, I will change the behavior to the following:
- If the user supplies a matrix, process as intended
- If the user supplies a vector, assume constant probabilities for each unit and potentially warn the user that this implicit assumption is being made (this should also allow users to generate degenerate categorical draws)
- If the user supplies something that is neither of these things, then it is invalid data and we should error.

I'll close the issue and commit the code change on the weekend if no one has feedback. Thanks.

**Comment by acoppock** [comment]
sounds right to me
