### ISSUE TITLE
sac_level behavior

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#152]
This does not work:

```
fabricate(
  upr = add_level(N = 2),
  lwr = add_level(N = 2),
  upr = modify_level(test = rnorm(N), by = "upr")
)

  upr       test
1   1 -0.9743328
2   2 -0.6136675
```

But this does:

```
fabricate(
  upr = add_level(N = 2),
  lwr = add_level(N = 2),
  NEW = modify_level(test = rnorm(N), by = "upr")
)

  upr lwr       test
1   1   1 -0.5193255
2   1   2 -0.2459346
3   2   3 -0.8427144
4   2   4 -1.0383925
```

Do I misunderstand how this works, or is this a bug?

**Comment by nfultz** [comment]
This is working as designed - internally, fabricate track each of the
levels generated.  When you specify `upr=modify_level` it loads `upr` and
modifies it, which only had two observations.  when you do `NEW =
modify_level()`, `NEW` was not an existing level to modify, so it will
create it based on the last active level (lwr) - I would suggest writing
this as `lwr=modify_level(by="upr")` as you probably don't need the NEW
level.

It would be nice if there were some plotting methods in fabricate that
would map this stuff out.

**Comment by graemeblair** [comment]
Thanks, this is super helpful. Make sense. Agreed on plotting.
