### ISSUE TITLE
correlate(draw_likert) would be nice

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/fabricatr#170]
via http://discuss.declaredesign.org/t/fabricating-correlated-likert-items/76

wire up draw_likert to be usable from correlate.

**Comment by WillemSleegers** [comment]
I second this; it would be great.

**Comment by graemeblair** [comment]
The new draw_likert function just cuts up a latent varaible, so you can use correlate to draw two correlated latent variables and then chop at will.
