### ISSUE TITLE
Add plots to time series vignette

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/fabricatr#184]
via the forums[1]

> 
> I have found the tutorial on Time series data with fabricatr very helpful, but I end up adding plots to the examples as these can make it much easier to understand how the code works. I’m sharing these in case others find it helpful - and I think it might be worth incorporating this kind of thing into the vignettes.
> For example, this code just creates a country label that combines each country with its associated parameters for the example of Multiple Units with Time Trends, and then plots the series for each country.
> 
> ```r
> panel_units$countrylabel <-paste0(panel_units$countries,': base=',round(panel_units$base_gdp,0),'; growth=',
> round(panel_units$growth_units,2),"; err=",round(panel_units$growth_error,2))
> ggplot(panel_units,aes(x=ts_year,y=gdp_measure,colour=countrylabel,group=countrylabel)) + geom_line()
> ```

[1]: https://discuss.declaredesign.org/t/suggestion-to-add-plots-to-vignettes/207

**Comment by graemeblair** [comment]
Thank you, we agree that would be a good addition. We're tryigng to avoid tidyverse dependencies still so closing for now.
