### ISSUE TITLE
Feature request: `draw_categorical()` returns a factor when using labels

### ISSUE THREAD

**Issue by davidchall** [DeclareDesign/fabricatr#186]
When using labels, I would expect `draw_categorical()` to return a factor vector, similar to how `draw_ordered()` behaves.

``` r
library(fabricatr)

labels = c("A", "B", "C", "D")

# ordered returns factor
x <- draw_ordered(x = rnorm(5), break_labels = labels)
x
#> [1] C C C B B
#> Levels: A B C D
class(x)
#> [1] "factor"

# categorical returns character
x <- draw_categorical(N = 6, prob = rep(0.25, 4), category_labels = labels)
x
#> [1] "D" "D" "D" "A" "A" "A"
class(x)
#> [1] "character"
```

<sup>Created on 2022-04-21 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by nfultz** [comment]
This is easy, I can take a look at it next week or you could prep a pr. The line to modify is here:

https://github.com/DeclareDesign/fabricatr/blob/66cf86d703f155db0050ca1547bdb1e0ab272f3e/R/variable_creation_functions.R#L235

**Comment by davidchall** [comment]
> Alternatively, I believe you could try passing in as.factor(labels), and then the result would also be a factor? Haven't tried myself.

Yes, this is what I've done in the short term. But if we can edit `draw_categorical()` then we can avoid creating the character vector and save on memory usage.
