### ISSUE TITLE
What to do when some variables are levels and others aren't

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/fabricatr#2]
The following use case is not handled by `fabricate_data`: 

```r 
population <- declare_population(
  N = 10^5,
  noise = rnorm(N),
  block = level(
    N = 5^4,
    block_effect = rnorm(N)
    )
)
pop <- population()
```

When not all options are levels then it goes to `fabricate_data_single_level_`, which throws the following error:
``` r 
 Error in paste(c(ID_label, "ID"), collapse = "_") : 
  argument "ID_label" is missing, with no default 
```
As an aside, I can't quite understand why it throws this error because `fabricate_data_single_level_` handles cases in which ID_label is NULL...

Anyway I see two solutions to the "not all variables are levels" problem (i.e. 
`if(any(options == "level") & !all(options == "level")`), happy to implement either of them: 
  1. We throw an error when the user uses any levels but doesn't have **all** variables as levels 
  2. (My preference:) We treat all variables in the non-level list as belonging to the same level (since we have an N), with the default level-ID, and merge in the other levels as we would otherwise do if those variables had been declared inside a `level()` wrapper.

**Comment by acoppock** [comment]
I think we had the intended to do (1) but didn't write a clear error :) - which is why it didn't work but gave you back hard to interpret junk.  

I'm open to (2), except we'd need to decide on a default - is the level higher or lower than the other args?

I guess I'd prefer to require that users explicitly have to explain all explain all levels as in (1).  GB?

**Comment by graemeblair** [comment]
I think the best way to do this is:

```
population <- declare_population(
  block = level(
    N = 5^4,
    block_effect = rnorm(N)
    )
  individuals = level(N = 10, noise = rnorm(N))
)
```

So I've added an error a la suggestion (1):
```Error in fabricate_data(N = 10^5, noise = rnorm(N), block = level(N = 5^4,  : 
  Arguments passed to ... must either all be calls to level() or have no calls to level().```
