### ISSUE TITLE
fabricate() hierarchical issues

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#22]
I was using fabricatr today and I may be missing something, but it appears the way fabricate() is handling hierarchical data is not working quite right:

```
> fabricate(
  regions = level(N = 3, gdp = rnorm(N)),
  districts = level(
    N = 2,
    var1 = rnorm(2)
  )
)

  regions         gdp districts       var1
1       1 -0.05955841         1  0.2869096
2       1 -0.05955841         2 -2.9556124
3       2 -0.07986005         3  0.2869096
4       2 -0.07986005         4 -2.9556124
5       3 -1.62880298         5  0.2869096
6       3 -1.62880298         6 -2.9556124
```

This should have produced different values of var1 in each district (it should have run rnorm(2) three times, once for each region). 

When a vector is provided that is too long, it used to use the first N values, but now incorrectly expands the dataset. The following could should also have a produced a dataset of length 6:

```
fabricate(
  regions = level(N = 3, gdp = rnorm(N)),
  districts = level(
    N = 2,
    var1 = month.abb
  )
)

   regions       gdp districts var1
1        1 -1.522291         1  Jan
2        1 -1.522291         2  Feb
3        2  1.498186         3  Mar
4        2  1.498186         4  Apr
5        3  0.330097         5  May
6        3  0.330097         6  Jun
7        1 -1.522291         1  Jul
8        1 -1.522291         2  Aug
9        2  1.498186         3  Sep
10       2  1.498186         4  Oct
11       3  0.330097         5  Nov
12       3  0.330097         6  Dec
```

@nfultz since Aaron isn't on tomorrow, would you be able to take a look?

**Comment by nfultz** [comment]
Based on the changelog, I think this never worked that way, because the `2` is hardcoded in there - I haven't tried it yet, but I *think* changing the `2` to an `N` will work because N is recalculated before actually evaluating the calls.  Either way, this would be a good unit test.

**Comment by graemeblair** [comment]
I tried it out on an old version and it functioned similarly (badly) in early versions too. Thanks for getting into it.

**Comment by aaronrudkin** [comment]
I am going to close this because the rewrite of fabricate will moot it -- and I think we decided to enforce N-sanity and avoid situations with reuse, wrapping, or other weirdness.
