### ISSUE TITLE
"Passthrough" resampling: Naming, Vignette, Documentation

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#25]
We have talked on and off about resampling that passes through levels of the data transparently. An example of this is "For each state, I wanted to resample 10 cities" or "For each school, I want to resample 10 students" -- this is different than resampling N cities or N schools, of course.

I have this implemented, but we should probably think a little bit about naming. Right now I'm calling this ALL_UNITS. In caps because I grew up on C-family languages which use all-caps variable names for constants or flags; and ALL_UNITS because you quite literally want all of the units, unchanged. The name could be longer (ALL_UNITS_AT_LEVEL) and more descriptive. We might also try PASSTHROUGH (The "through" / "thru" corruption in American English might make this non-obvious). There's also a question of whether there should be case sensitivity at all.

Finally, we need a tests (I will take care of these), a vignette entry (if we want to expose this functionality), and to update the documentation.

The current syntax is -- we should also talk about what we want to do here:
```
my_resample = resample(my_data, N=c(ALL_UNITS=TRUE, 5), ID_labels=c("state", "city"))
```

With this syntax, all of the implementation details are solved and pretty trivial (the TRUE will autoresolve to 1, the variable will set a names() on the vector unit, and we can read from there ignoring the number; all of the error handling doesn't need to be changed because the 1 is a positive numeric integer).

Since N can be a variable containing a vector, a directly provided anonymous vector, a scalar, etc. using NSE to capture the ALL_UNITS token is not ideal -- it's difficult to extract each value of a vector for individual NSE, where some are evaluated and some are deparsed.

If there are no suggestions on syntax, then I think the only thing I need from you guys is to give some thought about the vignette / documentation.

The code will be in a branch called passthrough_resample shortly.

**Comment by graemeblair** [comment]
Thanks, Aaron, this is great. I suggest

`my_resample = resample(my_data, N=c(ALL, 5), ID_labels=c("state", "city"))`

if that's possible?

**Comment by nfultz** [comment]
`ALL` should be possible if we choose a sentinel value that no sane user would use - `-20171101L` could be a good one ;). 

In that case where we aren't sneakily basing logic on the names attribute, what about using `names(N)` instead of ID_Labels:

```
my_resample = resample(my_data, N=c(state=ALL, city=5))
```

**Comment by graemeblair** [comment]
I like that syntax a lot, makes things much more clear (and less typing!).

**Comment by aaronrudkin** [comment]
I like this as well. I think really we've got two separate functions here -- one to allow names for N to be aliases for ID_labels, and one for the passthrough resampling to trigger with the magic constant ALL (and yes, I agree, since we need a magic constant it'll be easiest to map the constant to a large negative value internally, especially since we otherwise disallow negative numbers for N). I'll keep the latter in this issue and make a separate issue for the former.

**Comment by aaronrudkin** [comment]
The commit that implements Neal's syntax example is on the passthrough_resample branch.

Users can now specify names of levels to resample in the N vector (or continue to do so in the ID_labels vector -- we need to decide whether we will surface both options to users or not), and users can provide the value ALL if they want passthrough resampling. ALL is a magic constant which is exported so we shouldn't have any namespace issues. And we have tests to verify both that these functions work and that they fail as expected.

Now it's just the vignetting / documenting component.

**Comment by aaronrudkin** [comment]
I also updated the vignette.

**Comment by aaronrudkin** [comment]
As the PR for this merged, I will close the issue for now.

**Comment by graemeblair** [comment]
Separate issue for vignette improvements or we are good there?
