### ISSUE TITLE
I'd like to have n()

### ISSUE THREAD

**Issue by jaspercooper** [DeclareDesign/fabricatr#3]
... or something like it, such as the option to create "global variables", that are expressions run on the whole nested data.frame at once.

I want heterogeneous block sizes with a variable telling me the size of the block. Here are four ways I would like to be able to do that, none of which work at present:

``` r 
population <- declare_population(
  block = level(
    N =  10^4,
    block_effect = rnorm(N),
    # Method 1: pass block_size argument to lower level:
    n_1 = sample(
      x = 2:3,
      size = N,
      replace = TRUE
    )
    # And then pass this to the N argument for the individual level 
    ),
  individual = level(
    N = sample(
      x = 2:3,
      size = 10 ^ 4,
      replace = TRUE
    ),
   # Methods 2 and 3: create an n() function a la dplyr:
   n_2 = n(),
   n_3 = N,
   noise = rnorm(N)
  ),
  # Method 4: global variables
  global_variables = list(
    n_4 = group_by(block_ID) %>% mutate(n = n())
 )
)

```

At present I have to do this:

``` r 

# Blocks of two or three units
block_data <-
  data.frame(
    block_size = sample(
      x = 2:3,
      size = 10 ^ 4,
      replace = TRUE
    )
  )

population <- declare_population(
  block = level(
    level_data = block_data,
    block_effect = rnorm(N)
    ),
  individual = level(
    N = block_data$block_size,
    noise = rnorm(N)
  )
)

```

**Comment by jaspercooper** [comment]
It occurs to me that in DD at least we can declare global variables at the design declaration phase, but ultimately I think fabricatr should be able to do this too.

**Comment by acoppock** [comment]
In the interest of drastic simplification and not gumming up declare_population with bells and whistles, we removed all such features.  now a user would insert a custom DGP function.

library(DeclareDesign)
library(dplyr)

population <- declare_population(
  block = level(
    N =  10,
    block_effect = rnorm(N)),
  individual = level(
    N = sample(
      x = 2:3,
      size = 10,
      replace = TRUE
    )
))

my_fun <- function(data){
  data %>%
    group_by(block_ID) %>%
    mutate(block_size = n())
}


design <- declare_design(
  population, my_fun
)

design
