### ISSUE TITLE
Time series data

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#30]
@graemeblair suggested that Fabricatr should support the construction of time series data. I agree. I think at this juncture it is probably best to mark this as a post-CRAN submission task, in part because I need to think about what constructing time series data even looks like.

@nfultz wisely suggested that random walk data could be generated by doing i.i.d. random draws and then setting the observed value to the cumSum of the values up until that point -- but that more complicated time series models with actual structure would be slower.

I'm going to leave this as an open issue so people can suggest what they think time series data generation ought actually do. In other words, what are the ideal forms that the data takes. I have vaguely covered exponential smoothing and I've had a very cursory overview of AR/I/MA models but in part it's not clear to me whether these are convenient modelling assumptions or if we actually believe data is generated this way. What kinds of assumptions do users need to make about the memory of the process in order to generate data which flexibly resembles real-world data?

I would love anyone to suggest a MWE in base R of what some data might look like so I could adapt it to fabricatr and see what functions we need to do.

**Comment by graemeblair** [comment]
agreed this is post-CRAN but important

**Comment by graemeblair** [comment]
could you do an example (if one is not already in here) doing this with a simple time trend? I'd do:
(1) time series data with a time trend and other variables with a single unit;
(2) panel data with that overlaid with unit-specific time trends and universal time trend?

I think this is already possible with existing functionality and no need to do ARIMA or anything crazy, just literally how do you get the data to look right at first.

if this is already in the examples, lmk!

**Comment by graemeblair** [comment]
@aaronrudkin ping

**Comment by aaronrudkin** [comment]
Handling this today. Preliminary strategy is to write up both examples from @graemeblair's Jan 8th comment and then write up an example of using **forecast** with **fabricatr** for ARIMA data in the other packages vignette.
