### ISSUE TITLE
Private arguments to level functions

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#31]
This is just a placeholder issue to remind me that I currently have several private arguments in the suite of functions associated with levels and I have documentation telling users not to use them in order to silence the R CMD CHECK documentation warnings -- this should be replaced with CRAN-friendly public-facing documentation

**Comment by graemeblair** [comment]
This needs to get addressed now, right?

**Comment by aaronrudkin** [comment]
Not sure if it's blocking for CRAN but I just addressed it via some fiddling.
