### ISSUE TITLE
Weird behavior when user supplies an unnamed level argument and fabricate interprets it as a data input

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#32]
`fabricate(add_level(N = 5, gdp = rnorm(N)))` should fail because the level is not named. Instead, due to a variety of reasons (changes in how we handle invalid ID_label parameters), it works and produces a valid data frame -- because fabricate believes the add_level call is the data argument, evaluates it, gets a data frame back, and uses that as data, and then it's an empty fabricate() call with imported data.

On the other hand, this isn't necessarily incorrect behavior -- to the extent that someone ran an add level call outside fabricate (which we technically allow but do not suggest), they would get a data frame. And you can give fabricate a data frame as an anonymous first argument.

Attempting to do this with two levels will fail because the second anonymous level will parse an invalid N (and even if valid, would error because you provided data and N).

One fix for this is to move the data argument after the splat in the fabricate function definition, but this breaks the default compatibility with piping, so I won't do that.

This is an issue that I'm creating to remind myself to follow up on this. It might not actually be problematic behaviour, but it feels like it is. Notably, I need to check exactly where in the order of operations the check to ensure that a level call has a name occurs and why that doesn't fail here.

**Comment by graemeblair** [comment]
+1 that this behavior should not be allowed and an informative error should be thrown

**Comment by aaronrudkin** [comment]
Error handling was occurring at two spots in the path -- in the dispatch call before the level modification if you had a series of level calls, and in generating an ID variable if you had an anonymous single-level fabricate call. Because there wasn't additional error checking in actual function adding the level, this use case slipped through. Whoopsie! I'll have the commit fixing this before I do the merge request tonight.
