### ISSUE TITLE
User provides data, makes single-level modification, does not specify ID label

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#33]
One of the examples I use in the vignette is this:
```
simulated_quake_data = fabricate(data=quakes,
                                 fatalities = round(pmax(0, rnorm(N, mean=mag)) * 100),
                                 insurance_cost = fatalities * runif(N, 1000000, 2000000))
```

Basically, importing existing data (quakes is a dataset in base R), and adding new variables at that same level. If the user specifies an ID_label it will staple an ID label column with the name specified onto the dataset. If the user does NOT specify an ID_label, the call should:

1. Staple an ID_label with a default name (ID)
2. Assume the user does not require an ID_label and do nothing
3. Error
4. Warn
5. Other

I was doing (2) until I closed that last issue and now don't want any way for an add_level call (which is how this is processed internally) to not take an ID_label -- since this requires me either to do (1) or to make a special exception to do (2), I figured I'd take everyone's temperature.

Please vote below.

**Comment by graemeblair** [comment]
Not understanding. You write "If the user does NOT specify an ID_label, the call should:" -- could you edit to include an example of that code?

**Comment by aaronrudkin** [comment]
The above is intended to be an example.

Right now, when the user calls a single-level fabricate call (no level calls), one of several things can happen:

1. User does not import data, does not specify ID_label: A default ID column is added ("ID")
2. User does not import data, does specify ID_label: An ID column with the name specified in ID_label is added
3. User imports data, does specify ID_label: Check to see if ID_label is a column in the data, if so don't add anything, but make a note internally that that's a level (I keep a running tally of level names in the workspace, although they aren't presently important for any functioicate(Danality). If the ID_label is not a column in the data, create it.
4. User imports data, does not specify ID_label: This example

In the example above, I load data and add two column names, not specifying an ID_label. I can derive it from the name given to the variable the fabricate call returns to (i.e. create "simulated_quake_data" as a column); but this is often not the user's intent, and it wouldn't solve the dilemma when the fabricate call is run directly rather than returned to a variable. I could use the variable from which the data is loaded (i.e. create "quakes" as a column) -- but this doesn't solve it if the user directly specifies the data they're loading anonymously. Or I could default to "ID", or do nothing. In principle the user doesn't NEED an ID variable for single-leveled data.

The reason I think this is something worth wondering about is whether the user would expect that a fabricate call to add, say, N variables would actually add N+1 columns.

I guess in terms of MWEs, the following questions require an answer:
```
identical(fabricate(data=df), df) # TRUE or FALSE?
dim(fabricate(data=df))[2] == dim(df)[2] # TRUE or FALSE?
setdiff(colnames(fabricate(data=df)), colnames(df)) # What should this contain if anything?
```

This matters for our tidyverse selling point -- if the users repeatedly pipes from fabricatr to something in tidyverse to fabricatr again, mutating, summarizing, etc, are we going to keep stapling on ID columns?

```
fabricate(N=20, v1 = rnorm(N)) %>% mutate(v2 = v1 * 3) %>% fabricate(v3 = v2 * 3) %>% filter(v3 > 3) %>% fabricate(v4 = v3 * 3)
```

If I always try to staple on a new ID column on each import, this kind of workflow adds three ID columns, two identical, and one separate. Which leads me to a final question: when the user imports a data frame with a column called ID and does not specify ID_label; should we add our own ID (I have a fallback system that is smart enough to find an unused name) or assume the user has a column called ID and so is satisfied with their data as-is?

```
df = data.frame(ID = 1:10, X = rnorm(10))
colnames(fabricate(data=df, Y = 3*X))
```

None of these block functionality but it'll be nice to standardize the answers in terms of user expectation.

**Comment by graemeblair** [comment]
Ah. Thanks.

`identical(fabricate(data=df), df) # TRUE or FALSE?`

Yes. Don't add ID column in these cases. Do you agree, @aaronrudkin?

**Comment by graemeblair** [comment]
should this be closed?

**Comment by aaronrudkin** [comment]
This is done.

Possible behaviours:
- Import a data frame and do not make any changes: No ID column added
- Import a data frame and make changes, ID_label left blank or some name that is not in the df: ID column added
- Import a data frame and make changes, ID_label set to a column that already exists in the df: No ID column added.
