### ISSUE TITLE
draw_discrete - shouldn't have to pre/append +-Inf

### ISSUE THREAD

**Issue by nfultz** [DeclareDesign/fabricatr#35]
currently for `draw_discrete` you have to manually pre/append +- Inf to the breaks - this is non-ergonomic/ugly, and also means you have to set names separately on a different argument.

**Comment by aaronrudkin** [comment]
Fair point. I think I currently error if the breakpoints don't cover the data, but maybe the better point is to assume that the low breakpoint is always -Inf and the high always +Inf. When I pop back into code land I'll fix this quickly.
