### ISSUE TITLE
draw_discrete syntax

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#37]
@graemeblair expressed concern about the syntax of draw_discrete (specifically, us having overloaded "x"). I'm not sure there's an easy way around this -- if we disambiguate x, people will need to learn multiple names. We could use the splat to forcibly de-alias the argument and require users to go by position, but this is messy too. We're going to discuss this later, offering an issue for now so it doesn't get lost in the shuffle.

**Comment by nfultz** [comment]
`draw_binary` `draw_count` `draw_factor` etc - discrete is too vague.

**Comment by graemeblair** [comment]
+1

**Comment by aaronrudkin** [comment]
We now have: `draw_binary`, `draw_binomial`, `draw_count`, `draw_ordered`, and `draw_categorical` (in addition to `draw_binary_icc` and `draw_normal_icc`). This is just the base functionality from `draw_discrete` ported to new functions. See documentation for how I disambiguated the arguments. Open new issues if anyone is unhappy with syntax or wants functionality we don't have.

**Comment by graemeblair** [comment]
Awesome! Thanks Aaron. Is there any sense in combining `draw_binary` with `draw_binary_ICC`?
