### ISSUE TITLE
providing cluster means/probs to draw_icc_* in fabricatr

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#38]
`draw_normal_icc` and `draw_binary_icc` take x as the first arg which is the mean or probability for each cluster (or a single number to set them equal). This makes x not workable in `fabricate`, where you could have x per cluster but it'd be repeated across individual observations. Can we allow x to have the same length as cluster and figure out the cluster means using the two columns i.e. `unique(data[, clusters, x)])`?

**Comment by aaronrudkin** [comment]
Just to ensure I understand what you mean:

Our example is N=50 observations across n=5 clusters. Currently we allow x of length 1 (constant prob/mean across all clusters) or length 5 (one prob/mean for each cluster), and you're hoping to allow x of length 50, is that correct?

And in terms of implementation details, we would:

1) Fail if a given cluster has more than one value in this new auxiliary vector version of x
2) If not, discard down from length N to length n by using the unique call

**Comment by graemeblair** [comment]
Yes -- but I think what you should do is try to use `draw_normal_ICC` with multilevel data in `fabricate`. It currently isn't possible to do when only length 1 or length 5 are allowed.

Those checks seem right.

**Comment by graemeblair** [comment]
Is this addressed now?

**Comment by aaronrudkin** [comment]
This should be addressed with the discrete_rewrite branch I'm merging in in the next hour or so -- basically, I allow length(x) == N, but check to confirm uniqueness by cluster, as you suggested.
