### ISSUE TITLE
Cleanup refactor from Neal's code review

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#43]
Stuff from Neal's code review of the mega merge that we might reasonably consider outstanding business.:

1. Use of lists inside enviroments -- I assume @nfultz would rather switch to environments inside environments?
2. ~The shelving code could probably be abstracted into a helper function~
3. ~Split the level functions into separate files to keep file length manageable~
4. As per @nfultz, the `ordered_indices` line in cross_classify_helpers.R could be refactored out of the lapply into a sweep
5. ~As per @nfultz, the index_maps[] line (484-487 on the current fabricate.R, about a page down in `modify_level()` is an ugly hack.~

**Comment by graemeblair** [comment]
are these all things that will be fixed before v1? or these will not yield breaking changes?

**Comment by aaronrudkin** [comment]
None of these are breaking changes -- they are cosmetic code changes. I do not expect to implement them immediately. The double DF import thing (issue #39) might involve implementing the second item on the list, but regardless they will not impact any end user behaviour.

**Comment by aaronrudkin** [comment]
Second item on the list implemented.

**Comment by aaronrudkin** [comment]
Number 3 is done.

**Comment by aaronrudkin** [comment]
Number 5 is done -- somewhere around 10x speedup in rewriting the step when benchmarking the old way versus the new way on a synthetic 20,000 unit data-set.
