### ISSUE TITLE
Tolerance for correlations in cross_level tests

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#44]
Right now, a very small number of builds fail because the observed correlations are outside the tolerance levels I set. I think this is mostly a stochastic property and not anything not working (restarting the build will have it complete correctly), but I should look at this a little while later to ensure the tolerance is set to minimize this possibility.

**Comment by nfultz** [comment]
Maybe set the RNG seed in the test?

**Comment by graemeblair** [comment]
We didn't discuss this yesterday; will this be addressed before v1?

**Comment by aaronrudkin** [comment]
Yes. Neal is right, I should just set the RNG. To some extent the reason I didn't was to try to get a sense of how attenuated the observed data would be when I was figuring out the copulas, but builds shouldn't be breaking due to stochasticity.
