### ISSUE TITLE
argument name for icc

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#46]
Should we name the args `ICC` rather than `rho`?

**Comment by aaronrudkin** [comment]
Picking up on this now. I got the sense from earlier calls that you guys were uncertain about rho, but most of the specifications I could find online for similar stuff seemed to use it more generally. I am agnostic about the change. @nfultz Any practitioner experience here?

**Comment by graemeblair** [comment]
Why wouldn't we use ICC, though, since it is specifying the ICC?

**Comment by nfultz** [comment]
One justification would be that we are specifying the true population parameter, and by convention parameters are greek and summary statistics are english.

**Comment by graemeblair** [comment]
idk, this seems to add considerable confusion and is scary for non-technical users (ICC is already pretty bad). The help file says

`rho | A number indicating the desired ICC, if none is provided will default to 0.`

Seems like WYSIWG is a good rule.

**Comment by aaronrudkin** [comment]
My preference on this was weak enough that I'll fold and push this during the week. Please proceed with rho and I will change before submission.

**Comment by aaronrudkin** [comment]
This is in a forthcoming commit.
