### ISSUE TITLE
Vignettes for working with other data generating packages

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#49]
I just wrote a very short two-example vignette for working with wakefield. The two examples are: 1) Using wakefield when generating a variable within a fabricate call; 2) piping wakefield data frame (tibble) output into fabricate to then nest data.

Let's use this issue to track other packages we want to work with and what we think a MWE for using that package's functionality is.

**Comment by aaronrudkin** [comment]
@nfultz recommended 

[x] wakefield
[ ] datasynthr
[ ] babynames
[ ] UScensus2010

**Comment by aaronrudkin** [comment]
datasynthR is mostly discontinued (not on CRAN, issues open from 2014 asking for R 3.2 support) but I did write a little tutorial for how we might use some of their stuff -- also submitted a pull request since one of their core functions is materially broken.

**Comment by graemeblair** [comment]
Hm. I think if it's broken and discontinued, let's exclude it. Let's include things that look good and work, not feel we need to be comprehensive.
