### ISSUE TITLE
argument names singular/plural

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#51]
We have a few arg names for the variable creation functions that are plural -- `probs`, `means`, etc. -- which I think are inconsistent with base functions such as rnorm/rbinom, i.e. we have 

`draw_binary(N = N, probs = 0.2)`

whereas base R has:

`rbinom(n, size, prob)`

Suggest we make them all singular?

**Comment by aaronrudkin** [comment]
No strong preference here. The trade-off is the hinting of the plural argument that you can provide multiple things versus breaking compatibility with base R, and I agree that the former might be more of a cost than a benefit. I will commit this after you show the guys but before submission.

**Comment by aaronrudkin** [comment]
Obvious to make singular:
probs -> prob
means -> mean

Less obvious:
trials -> trial
breaks -> break
break_labels -> break_label

Thoughts?

**Comment by graemeblair** [comment]
I like breaks and break_labels (esp because we use labels plural throughout the ddverse) 

less sure about trials, can you see if there's an example of this elsewhere in base?

**Comment by aaronrudkin** [comment]
I don't see "trials" versus "trial" used in any base packages so I will leave as is. I also altered "x" in draw_binary_icc to "prob" and "x" in draw_normal_icc to "mean". 

Where did we end up coming down on "clusters" versus "cluster"?

**Comment by graemeblair** [comment]
we're at `clusters` in randomizr and estimatr

**Comment by aaronrudkin** [comment]
Super, then this is done.
