### ISSUE TITLE
Quicker generation of correlated variables

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#55]
@acoppock requested a quick helper function that would enable something like this:
```
example = fabricate(
  respondent = add_level(attitude_immigration = draw_ordered(...),
                         attitude_defence = draw_ordered(..., 
                                                         correlated=f(attitude_immigration, rho=0.7)))
)
```

I agree this would be super handy. 

The two methodological issues I think we'd need to clear to make this possible:
1. Code introspection to confirm that the DGP specified in `attitude_defence` is exchangeable so that we can use the copula strategy to link the two resulting variables. In other words, if someone gives us `attitude_defence = draw_ordered(rnorm(N, mean=how_conservative_am_i), correlated=f(attitude_immigration, rho=0.7))`, the observation-level dependence of the variable on other variables makes the draw have a deterministic characteristic that is incompatible with the correlation specified.

2. Ensuring that for low Ns, at least, we generate a superpopulation before doing the correlated join so that we don't suffer from data density issues degrading the correlation.

Most of the copula code from the cross_level joins can be reused here.

Milestone: post-CRAN Future

**Comment by graemeblair** [comment]
This is a great solution to the ideas Jasper raise about drawing correlated variables -- this splits the problem into separate vars, so works with our single-variable-creator setup. Two thumps up!

**Comment by aaronrudkin** [comment]
The code for this is done-ish. Our process is this:

Given: Empirical RV X; desired rank correlation coefficient rho; parameterization for distribution Y

Process: X -> Get the quantiles of each observed X in the empirical distribution of X -> Inv. CDF -> X in standard normal form -> Y_{std} = rho * X_{st + Normal(0, (1 - rho^2)) -> Std. Normal CDF -> Y quantiles -> from from Y's CDF by quantile

We've also discussed naming and implementation.

**Comment by aaronrudkin** [comment]
Just pushed this to `draw_corr` branch, along with tests and vignettes and documentation (although no in-code examples; I will punt until we solve naming). 

Implementation info:
- I implemented it for draw_binary, draw_binomial, and draw_count. Obviously it's not meaningful for draw_categorical.
- I have not yet implemented it for `draw_ordered` (and aliases like `draw_likert` and `draw_quantile`). The issue here is that it's not actually clear how to map the quantiles of the Y variable onto the distribution of the ordered variable without an explicit CDF -- basically, suppose the correlate function tells me I should draw a survey response at the 90th quantile; the minimum information I need to change that into a Likert is both a CDF and breaks. I could assume that the CDF is standard normal, but the user would need to know I'm assuming that and still provide breaks. 
- I am opening a separate issue for what to do about R's reference distributions.

**Comment by graemeblair** [comment]
Given conceptual difficulty in how users should specify, doing ordered seems "too hard" for us so propose we just abandon. We help you when it's obvious what we'd ask you.

**Comment by aaronrudkin** [comment]
To other observers, GB and I just discussed this and decided not to support `draw_ordered`. The desired way for a user to do this would be to have the user create a correlated latent variable, and then pass that to draw_ordered -- this skips the awkward step of either assuming a CDF or passing a CDF and breaks. As a result, the feature is complete except for the result of #84 -- we can continue discussion there.
