### ISSUE TITLE
Vignette for common social science variables

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#56]
This is stubbed, adding to remind myself to address. The stub page has a target date of Wednesday.

**Comment by aaronrudkin** [comment]
The first pass of this will be:
- [x] Binary outcomes (example: Turnout)
- [x] Ordered outcomes (example: Mayoral job approval)
- [x] Likert as a quick wrapper
- [x] Categorical outcomes (example: Ethnicity in Kenya -- this isn't really an outcome example, although some outcomes are categorical; not sure if I should update this)
- [x] Truncated outcomes (example: Government efficacy 0-100 scale + treatment effect)
- [ ] Count outcomes and skewed distributions (examples: Reported violence in conflict zones and income)
- [x] Kicker to other tutorials you might be interested in

For subsequent examples, please open another ticket to get them added to the list.

**Comment by graemeblair** [comment]
Almost done! Awesome!
