### ISSUE TITLE
need to find a way to allow outcomes i.e. in declare_potential_outcomes() not to be at the lowest level

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#6]
Hierarchy is created nicely in declare_population, but currently the way we recommend using declare_potential_outcomes() just creates outcomes at the lowest level. If it's using only covariates used in higher levels, the outcome may respect the hierarchy. However, if it has a stochastic component such as rbinom(), it will implicitly be drawing that outcome at the bottom of the hierarchy even if the probabilities are created using hierarchical variables (i.e. if you set the probability to vary by village, you would want rbinom() in some cases to be a village-level binary outcome -- but instead it will draw at the individual level). Let's make a way to do this neatly! Should be an easy extension of the use of level().

**Comment by acoppock** [comment]
In the past, we’ve thought of such things as being “unobservable features of the population”, i.e., you make the cluster-level shock to the outcome in the population, then stipulate that it’s correlated with POs in the POs function.  

Is there a good argument not to leave it like that?

Alex

**Comment by graemeblair** [comment]
I agree that's very simple, but when you want to have any kind of stochastic potential outcome, i.e. a binary outcome drawn from a latent probability defined in the population, it becomes a problem. I think it makes the whole thing much less useful if lots of stuff has to be artificially in the population even though it more logically is a potential outcome.

I think we could probably do something *very very simple* that would allow you to say, draw this in the village level.  Maybe:

`declare_potential_outcomes(var = rnorm(N), level_ID = village_ID)`

?
