### ISSUE TITLE
arg names in draw_binary() etc. with links

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#65]
When we have a function like `draw_binary` with a `link` argument, right now we renamed `x` to `prob`, even though if you change `link` to be `logistic` for example, prob will have to be the latent var. I thought we'd decided to include `prob` but also `latent` or something like that (and it checks consistency between args. 

Current circumstance of providing `draw_binary(prob = runif(N), link = 'logistic')` does not seem right.

**Comment by aaronrudkin** [comment]
I agree that this is awkward; but I am unsure whether adding a different set of arguments solves more awkwardness than it causes. Any input from the rest of the team? @acoppock @nfultz @lukesonnet

**Comment by graemeblair** [comment]
I think having `prob` be the argument isn't a good option (it's not just awkward, it's wrong for the other cases), but open to others.

**Comment by lukesonnet** [comment]
`latent` or `parameter` are better (?), we could allow `prob` if it's actually a probability?

**Comment by nfultz** [comment]
how about `prob=link(latent)` in the formals?

**Comment by aaronrudkin** [comment]
I just wanted to follow up on this to say that Neal's idea is a good and I'm going to assign this.

**Comment by aaronrudkin** [comment]
This is done. The new syntax for using a link with `draw_binomial` is:

```
N = 100
var = draw_binomial(latent = rnorm(N), link = "probit")
```

It ended up being a little more of a hack that we originally thought, but it works. Docs are updated as well.
