### ISSUE TITLE
FasterWith -> Enhances

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#72]
for next version suggest we add enhances: to replace the lost fasterwith: info in DESCRIPTION

**Comment by aaronrudkin** [comment]
My understanding is that "Enhances" is when our package modifies an external package to add functionality; here we give nothing back to e.g. `data.table`. From r-pkgs:

> Enhances: packages listed here are “enhanced” by your package. Typically, this means you provide methods for classes defined in another package (a sort of reverse Suggests). But it’s hard to define what that means, so I don’t recommend using Enhances.

now, given the vague definition I'm OK with departing from the norm if we want to, but just wanted to flag this before doing anything.

**Comment by graemeblair** [comment]
Got it. Thanks.
