### ISSUE TITLE
Unhappy with ID column stapling

### ISSUE THREAD

**Issue by aaronrudkin** [DeclareDesign/fabricatr#77]
MWE:
```
  df <- fabricate(N = 2, Y = 10)
  df2 <- fabricate(data = df, Y2 = Y + 1)
  ncol(df2)
```

In general we do want **fabricatr** to staple an extra ID column onto imported data; but in this specific case, it results in two identical columns. If the user explicitly sets an ID_label, this will of course not happen.

Proposal: Use a heuristic to check if any existing column on the imported data is exactly identical to the proposed ID column, and if so, don't add one on.

This is a mildly breaking change in that the data being output is not exactly identical to the data being output without this change, but I'd rather mildly break now than mildly break later and I'm reasonably confident no real users are impacted by this.

**Comment by nfultz** [comment]
how about we tag the id column with an "id" class or something, then look
for that - it would be less brittle than checking names.

**Comment by aaronrudkin** [comment]
I have to be a little craftier than tagging the ID column because we also want this behaviour to apply to data being imported that was not generated in **fabricatr** to begin with (although there may be a slight efficiency boost to use classes or attributes for large data generated with fabricatr and then re-imported, so I will probably implement @nfultz's suggestion anyway.)

The full rule hierarchy is, with the new changes in bold:
- User explicitly names ID_label, and a column exists with that name -> Add nothing
- User explicitly names ID_label, that column does not exist -> Add ID column with that name
- Fabricate call does not modify anything -> Add nothing
- **ID_label left blank, and there's a column whose data matches the ID column we would add -> Add nothing**
- ID_label left blank, **and no column that matches the would-be ID data** -> Add ID column with name "ID", "fab_id_1", "fab_id_2", "fab_id_3", "fab_id_4", or "fab_id_5" -- whichever is the first available name.

**Comment by graemeblair** [comment]
@nfultz and I talked about this yesterday, and I'm not sure if this is caused by declare_potential_outcomes or fabricatr or both, but your "fab_id" column sticks around unwanted in this example:

```
population <- declare_population(
   N = 2100, 
   noise = rnorm(N))

potential_outcomes <- declare_potential_outcomes(
  Y_Z_0 = noise,
  Y_Z_1 = noise + .25)

design <- declare_design(
   population, potential_outcomes)

draw_data(design) %>% head
```

**Comment by aaronrudkin** [comment]
Note: We have added one more step here; if the user passes `NA` as ID_label, no ID label will be grafted on.
