### ISSUE TITLE
bug when level above is modify_level

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#80]
I'm not sure exactly what's going on here (if modify_level being above matters, having data provided, or if just not having an add_level is the problem), but this works:

```
fabricate(
  city = add_level(
    N = 10,
    city_var = rnorm(N),
    new_city_var = rnorm(N),
    city_name = letters[1:10]
  ),
  neighborhood = add_level(
    N = sample(20:50, N, replace = TRUE)
  )
)
```

And the same neighborhood specification with same size level above it does not work:

```
cities <- data.frame(city_var = rnorm(10), city = letters[1:10])

fabricate(
  data = cities,
  city = modify_level(
    new_city_var = rnorm(N)
  ),
  neighborhood = add_level(
    N = sample(20:50, N, replace = TRUE)
  )
)
```

**Comment by aaronrudkin** [comment]
I see the cause of this bug and have a fix.

Diagnosis:
In the code that checks if N is sane (i.e. if N is either 1 or the length of the level being nested under), we need to detect the last level in the data to see which level it's being nested under. There is an edge case with imported data where this fails.

MNWE at time of submission:
```
df1 = fabricate(N = 3, ID_label = "city")
df2 = fabricate(df1, neighborhood = add_level(N = c(10, 20, 30)))
```

Fix: A relatively simple detection for being in this state and using the `nrow` of the whole data frame as a guide for how many units are in the level above. Commit should be up in a few minutes.
