### ISSUE TITLE
non-standard behavior with variables of length 1

### ISSUE THREAD

**Issue by acoppock** [DeclareDesign/fabricatr#88]
we error if you do:

```
dat <-
  fabricate(
    schools = add_level(20, 
                        high_quality = rbinom(N, 1, .5)),
    students = add_level(10, 
                         D0 = 0
                         D1 = rbinom(n = N, size = 1, prob = .90))
    )
  )
```

but not if you do:
```
dat <-
  fabricate(
    schools = add_level(20, 
                        high_quality = rbinom(N, 1, .5)),
    students = add_level(10, 
                         D0 = rep(0, N),
                         D1 = rbinom(n = N, size = 1, prob = .90))
    )
  )
```

`data.frame` and `data_frame` both let you give a variable that is of length 1 and it gives it to all obs, and I think we should too!

**Comment by aaronrudkin** [comment]
This is supposed to work; although we generally override R's recycling, variables of length 1 are a special case that we are supposed to expand. Will test when I get the chance and fix.

**Comment by aaronrudkin** [comment]
Ah, yes, I see what's going on here -- there's a separate check for valid N length when dealing with nested data, and that doesn't have an exception for length 1. Should be a quick fix tomorrow.

**Comment by aaronrudkin** [comment]
Fixed in branch `final_fix`, will be merged in to master today.
