### ISSUE TITLE
draw from multivariate distributions

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#93]
Proposal to create infrastructure for allowing and then naming drawing multiple variables from multivariate distributions in other functions. We wouldn't write any multivariate distributions (already good in the ecosystem!) just infrastructure.

Proposed syntax:

```
fabricate(
  N = 500,
  cbind(my_var1, my_var2, my_var2) = mass::mvrnorm(n = N, mu = rep(0, 2), matrix(c(10,3,3,2),2,2))
)
```

**Comment by aaronrudkin** [comment]
So here are the considerations here:

1. Allowing support for RHS functions which return data structures other than vectors to a map of variables on the LHS is doable, but we're going to have hurdles about all the different types of data structures they might be, and the syntax on the LHS. Depending on the subset of functionality we want to support here, this can be now or later.

2. Second, I know one of the reasons for this is allowing arbitrary distributions on the RHS, so we should also have a wrapper that allows people to generate multiple arbitrarily distributed arbitrarily correlated arbitrarily parameterized variables at the sample time. This is definitely a future issue.

**Comment by nfultz** [comment]
I would recommend a nesting unapproach - data.frames can contain
data.frames/matrices as a column - see for example
https://github.com/nfultz/ec2instances.info - don't  need special cases or
weird/brittle syntax.
