### ISSUE TITLE
allow unbalanced panels in cross_levels

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#94]

**Comment by aaronrudkin** [comment]
The main challenge here that prevented me from implementing it in the first pass is thinking about how to specify imbalance: we need to say which of the constituent levels is the "take all" (countries) and which is the imbalanced one (years), and the imbalance is not just about "how many obs do we have", but also about "where is the start and end" -- imbalanced CY panels are not typically "we have a random number of years for all countries", but rather "some countries enter into the panel later, some drop out earlier, and there might be some missingness in the middle". 

I'm happy to do a naive version where you get a random assortment of years based on a vector that specifies some Ns, but I would think this is probably less helpful than what people would currently do; generate a df with fabricatr and then use some dplyr-fu to remove cases they don't want.

Accepting input.

**Comment by nfultz** [comment]
It would be easier to build the full panel, and drop rows at a later step -
imagine someone had ragged data Country  (USA, canada) x Year (1980, 1990,
2000, 2010) . Generate all eight row, the user can always drop canada-1980
or whatever later, in the next step - I would argue that canada-1980
platonically existed (which is the realm of fabricatr /
declare_population), just that they failed to capture it in their data
collection process (the realm of declare_sampling etc). As a rule,
fabricatr adds rows, not drops them.

**Comment by aaronrudkin** [comment]
Right, this was my thought -- you could generate the full panel and drop later; and then you could make use of country level covariates to hint at how you'll drop later (i.e. have min_year and max_year for each country and use dplyr functions to check if the current year is within the range). Obv it would not be efficient to do random missingness this way.

Still might merit doing an example in the panel vignette about HOW they'd do this, but my inclination would be that we're not great at doing it ourselves inside fabricatr.

Thanks for feedback Neal.

**Comment by graemeblair** [comment]
@nfultz is this addressed in recent changes? I don't think so, but wanted to check. thanks.
