### ISSUE TITLE
helpful error/warning about sigma matrix for link_levels

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#95]
If we can process the sigma matrix and identify cases where linking levels will not be possible (if not positive semi-definite?) then let's do that when they run it and so it is spit out when you run declare_population if possible rather than each time it simulates it. So this may be really about handling in declare_population.

**Comment by aaronrudkin** [comment]
I had thought there was a set of restrictions other than PSD on a valid correlation matrix, but if it ends up just being PSD then this check will be easy. If anyone faster than me has a cite for this I'll steamroll ahead; but if not I'll do research ASAP and get this warning in.

**Comment by nfultz** [comment]
I think if people pass in Sigma, we should throw an error if low-rank
chol() fails, if they pass in chol(Sigma) assume they know what they are
doing.

**Comment by aaronrudkin** [comment]
I'm trying to do this and am not sure if `chol(Sigma)` is what we want. Cholesky decomposition requires a positive definite matrix and correlation matrices can be positive semi-definite (e.g. `matrix(c(1, 0, 0, 0, 1, 1, 0, 1, 1), byrow=TRUE, ncol=3, nrow=3)` is a valid correlation matrix)

`chol(Sigma)` on that matrix will fail but it should be fine for the correlation; `all(eigen(Sigma)$values >= 0)` should be a reliable check for PSD matrices. 

It does look like, based on some searching, that it's demonstrable than being PSD and having all entries between -1 and 1 is sufficient for something to be a correlation matrix, so I'll go ahead and implement that, yeah?

**Comment by aaronrudkin** [comment]
Current error stack for sigma, each with their own descriptive errors:
1. Error if matrix is non-square or diagonal contains a number other than 1
2. Error if any cells are outside [-1, 1]
3. Error if matrix is not PSD

Just need to write tests.

**Comment by aaronrudkin** [comment]
LOL my error handling errors if you get complex eigenvalues, one sec.

**Comment by nfultz** [comment]
Use chol(pivot=TRUE)  and permute the random draws appropriately to deal
with linearly dependence.
