### ISSUE TITLE
add sampling weights to resample_data?

### ISSUE THREAD

**Issue by graemeblair** [DeclareDesign/fabricatr#96]

**Comment by aaronrudkin** [comment]
In the single level case this is fairly simple (just take a vector of length N); it ends up being a little more complicated in the multiple level balanced case, and very complicated in the multiple level stochastic case. It may be a failure of my imagination, but I'd like someone who had a clear use case for this to explain to me what kind of weight data we might think users would provide in the complex cases before I think about laying down a UI that enables it.

**Comment by nfultz** [comment]
For above complicated hypotheticals, can't you can already do that with
randomizr and elbow grease? It should be fewer than three lines of code.
